name: Validate

on: push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
